INSERT INTO medico (
                       name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       phone,
                       street_address,
                       number_address,
                       zip_code,
                       city,
                       state,
                       country,
                       especialidade,
                       crm,
                       turno
                   )
                   VALUES (
                       "Josival",
                       60,
                       "masc",
                       "021.111.222-45",
                       "Josefina",
                       "Florisval",
                       "josival@gmail.com",
                       "48922244655",
                       "Rua da Catarina",
                       "258",
                       "8822266",
                       "Florianópolis",
                       "SC",
                       "Brasil",
                       "Ortopedista",
                       "002556-85",
                       "Noturno"
                   );
                   
INSERT INTO medico (
                       name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       phone,
                       street_address,
                       number_address,
                       zip_code,
                       city,
                       state,
                       country,
                       especialidade,
                       crm,
                       turno
                   )
                   VALUES (
                       "Pedro",
                       53,
                       "masc",
                       "044.217.658-89",
                       "Joseli",
                       "Flores",
                       "pedro@gmail.com",
                       "48988552244",
                       "Rua da saida",
                       "6568",
                       "8822266",
                       "Florianópolis",
                       "SC",
                       "Brasil",
                       "Ortopedista",
                       "0665465-65",
                       "Vespertino"
                   );
				   
				   INSERT INTO medico (
                       name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       phone,
                       street_address,
                       number_address,
                       zip_code,
                       city,
                       state,
                       country,
                       especialidade,
                       crm,
                       turno
                   )
                   VALUES (
                       "Andre",
                       39,
                       "masc",
                       "034.328.852-69",
                       "Joana",
                       "Paulo",
                       "andre@gmail.com",
                       "48996886622",
                       "Rua da Dois",
                       "222",
                       "222222-22",
                       "Florianópolis",
                       "SC",
                       "Brasil",
                       "Cirurgião",
                       "023658-85",
                       "Matutino"
                   );
                   
INSERT INTO medico (
                       name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       phone,
                       street_address,
                       number_address,
                       zip_code,
                       city,
                       state,
                       country,
                       especialidade,
                       crm,
                       turno
                   )
                   VALUES (
                       "João",
                       33,
                       "masc",
                       "044.217.658-89",
                       "Angela",
                       "Henrique",
                       "joao@gmail.com",
                       "48998526677",
                       "Rua da Margarida",
                       "785",
                       "8806599",
                       "Florianópolis",
                       "SC",
                       "Brasil",
                       "Pediatra",
                       "032589-88",
                       "Noturno"
                   );

select * from medico;